name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install root deps
        run: npm ci
      - name: Install workspaces deps
        run: npm run install --workspaces
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build Frontend
        run: npm run build